force-app/main/default/objects/Borrower__c/Borrower__c.object-meta.xml
<CustomObject>
    <label>Borrower</label>
    <nameField>
        <displayFormat>Bid-{000}</displayFormat>
        <label>Borrowed ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Borrowers</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Borrower__c/fields/Book__c.field-meta.xml
<CustomField>
    <fullName>Book__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Book</label>
    <referenceTo>Book__c</referenceTo>
    <relationshipLabel>Borrowers</relationshipLabel>
    <relationshipName>Borrowers</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Borrower__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Borrow</fullName>
            </value>
            <value>
                <fullName>Not Returned</fullName>
            </value>
            <value>
                <fullName>Return Pending</fullName>
            </value>
            <value>
                <fullName>Returned</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/RecordCount.cls
public with sharing class RecordCount {
 
    @AuraEnabled(cacheable=true)
    public static integer getFacultyValue() {
        integer faculty ;
        faculty=[SELECT count() FROM User where Profile.Name ='System Administrator'];
        return (faculty);
    }
    @AuraEnabled(cacheable=true)
    public static integer getStudentValue() {
        integer studnet ;
        studnet=[SELECT count() FROM User where Profile.Name ='Standard Platform User'];
        return (studnet);
    }
    @AuraEnabled(cacheable=true)
    public static Decimal getBooksValue() {
        Decimal books=0 ;
        for( Book__c b:[SELECT Quantity__c FROM Book__c ])
        {
            books=books + b.Quantity__c;
        }
        return (books);
    }
    @AuraEnabled(cacheable=true)
    public static integer getBookIssuedValue() {
        integer booksissued ;
        booksissued=[SELECT count() FROM Borrower__c where Status__C !='Returned'];
        return (booksissued);
    }
}