force-app/main/default/objects/Borrower__c/Borrower__c.object-meta.xml
<CustomObject>
    <label>Borrower</label>
    <nameField>
        <displayFormat>Bid-{000}</displayFormat>
        <label>Borrowed ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Borrowers</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Borrower__c/fields/Bill_Ammount_B__c.field-meta.xml
<CustomField>
    <fullName>Bill_Ammount_B__c</fullName>
    <formula>IF( AND( ISNULL( Days_Remaining_to_Return_Book__c ), Date_of_Return_B__c  &gt;  Date_To_Be_Returned__c )  , MCEILING((Date_of_Return_B__c  - Date_To_Be_Returned__c))*2 , 
 IF((TODAY()-  Date_To_Be_Returned__c )&gt;0, MCEILING((TODAY()-  Date_To_Be_Returned__c ))*2, 0))</formula>
    <label>Bill Ammount B</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Borrower__c/fields/Book__c.field-meta.xml
<CustomField>
    <fullName>Book__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Book</label>
    <referenceTo>Book__c</referenceTo>
    <relationshipLabel>Borrowers</relationshipLabel>
    <relationshipName>Borrowers</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Borrower__c/fields/Borrowed_By__c.field-meta.xml
<CustomField>
    <fullName>Borrowed_By__c</fullName>
    <formula>CreatedBy.FirstName</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Borrowed By</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Borrower__c/fields/Date_of_Issue_B__c.field-meta.xml
<CustomField>
    <fullName>Date_of_Issue_B__c</fullName>
    <label>Date of Issue</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Borrower__c/fields/Date_of_Return_B__c.field-meta.xml
<CustomField>
    <fullName>Date_of_Return_B__c</fullName>
    <formula>IF(ISPICKVAL( Status__c , &quot;Returned&quot;),
   LastModifiedDate, null)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Date of Return B</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Borrower__c/fields/Date_To_Be_Returned__c.field-meta.xml
<CustomField>
    <fullName>Date_To_Be_Returned__c</fullName>
    <formula>Date_of_Issue_B__c +30</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Date To Be Returned</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Borrower__c/fields/Return_Book__c.field-meta.xml
<CustomField>
    <fullName>Return_Book__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Return Book</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Borrower__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Borrow</fullName>
            </value>
            <value>
                <fullName>Not Returned</fullName>
            </value>
            <value>
                <fullName>Return Pending</fullName>
            </value>
            <value>
                <fullName>Returned</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/GetBorrowerController.cls
public without sharing class GetBorrowerController {
    @AuraEnabled
    public static list<Borrower__c> getBorrow(string BName){
        String userProfileName = [select Name from profile where id =: userinfo.getProfileId()].Name;
        String usrname= UserInfo.getFirstName();
        if(userProfileName == 'System Administrator'){
            if(BName != null ){
                string ac= Bname+'%';
                //System.debug('if:::'+[Select Name,Bill_Ammount_B__c,Borrowed_By__c ,Date_of_Issue_B__c ,Date_of_Return_B__c,Date_To_Be_Returned__c,Status__c,Book__r.Name  From Borrower__c ]);
                return [Select Id,Name,Bill_Ammount_B__c,Borrowed_By__c ,Date_of_Issue_B__c ,Date_of_Return_B__c,Date_To_Be_Returned__c,Status__c,Book__r.Name  From Borrower__c where Borrowed_By__c LIKE:ac OR Book__r.Name LIKE:ac  order by Name ];
            }
            else{
                //System.debug('else:::'+[Select Name,Bill_Ammount_B__c,Borrowed_By__c ,Date_of_Issue_B__c ,Date_of_Return_B__c,Date_To_Be_Returned__c,Status__c,Book__r.Name  From Borrower__c ]);
                return [Select Id,Name,Bill_Ammount_B__c,Borrowed_By__c,Date_of_Issue_B__c ,Date_of_Return_B__c,Date_To_Be_Returned__c,Status__c,Book__r.Name  From Borrower__c ];
            }
        }
        else{
            if(BName != null ){
                string ac= Bname+'%';
                //System.debug('if:::'+[Select Name,Bill_Ammount_B__c,Borrowed_By__c ,Date_of_Issue_B__c ,Date_of_Return_B__c,Date_To_Be_Returned__c,Status__c,Book__r.Name  From Borrower__c ]);
                return [Select Id,Name,Bill_Ammount_B__c,Borrowed_By__c ,Date_of_Issue_B__c ,Date_of_Return_B__c,Date_To_Be_Returned__c,Status__c,Book__r.Name  From Borrower__c where Borrowed_By__c LIKE:usrname AND Book__r.Name LIKE:ac order by Name ];
            }
            else{
                //System.debug('else:::'+[Select Name,Bill_Ammount_B__c,Borrowed_By__c ,Date_of_Issue_B__c ,Date_of_Return_B__c,Date_To_Be_Returned__c,Status__c,Book__r.Name  From Borrower__c ]);
                return [Select Id,Name,Bill_Ammount_B__c,Borrowed_By__c,Date_of_Issue_B__c ,Date_of_Return_B__c,Date_To_Be_Returned__c,Status__c,Book__r.Name  From Borrower__c where Borrowed_By__c=:usrname];
            }
        }
        
    }
    
    @AuraEnabled
    public static list<Borrower__c> getBookByid(string ID){
        return [Select Id,Name,Bill_Ammount_B__c,Borrowed_By__c,Date_of_Issue_B__c ,Date_of_Return_B__c,Date_To_Be_Returned__c,Status__c,Book__r.Name  From Borrower__c where Id=: ID ];
    }
    
    @AuraEnabled
    public static void editBorrowRecord(string bid){
        Borrower__c borrowertoUpdate;
        borrowertoUpdate=[Select Status__c from Borrower__c where Name=: bid LIMIT 1 ];
        borrowertoUpdate.Status__c='Return Pending';
        borrowertoUpdate.Return_Book__c=true;
        update borrowertoUpdate;
        
    }
    
    
}