force-app/main/default/objects/Borrower__c/Borrower__c.object-meta.xml
<CustomObject>
    <label>Borrower</label>
    <nameField>
        <displayFormat>Bid-{000}</displayFormat>
        <label>Borrowed ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Borrowers</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Borrower__c/fields/Book__c.field-meta.xml
<CustomField>
    <fullName>Book__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Book</label>
    <referenceTo>Book__c</referenceTo>
    <relationshipLabel>Borrowers</relationshipLabel>
    <relationshipName>Borrowers</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Borrower__c/fields/Date_of_Issue_B__c.field-meta.xml
<CustomField>
    <fullName>Date_of_Issue_B__c</fullName>
    <label>Date of Issue</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Borrower__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Borrow</fullName>
            </value>
            <value>
                <fullName>Not Returned</fullName>
            </value>
            <value>
                <fullName>Return Pending</fullName>
            </value>
            <value>
                <fullName>Returned</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/BorrowBooks.cls
public with sharing class BorrowBooks {
    @AuraEnabled
    public static Borrower__c getBook(string bookID, Date issueDate, String stat){
        try {
            Borrower__c b = new Borrower__c();
            b.Book__c = bookID;
            b.Date_of_Issue_B__c=issueDate;
            b.Status__c='Not Returned';
                insert b;
                return b;
            
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }
}